spring:
  profiles:
    active: local
  application:
    name: steam-shop
  mail:
    host: host
    port: 777
    username: email
    password: pwd
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
    expiration-days: 12
  datasource:
    url: db_url
    username: db_username
    password: db_password
    driver-class-name: org.postgresql.Driver
server:
  port: 7777
s3:
  bucket: bucket
  endpoint: endpoint
  region: region
  access-key: akey
  secret-key: skey
jwt:
  secret: secret_key
  cookieName: cookie_name
  expiration-days: 30
shop:
  id: 1212
  token: token
  return-url: https://return-url.com/success
