spring:
  profiles:
    active: local
  application:
    name: steam-shop
  datasource:
    url: db_url
    username: db_username
    password: db_password
    driver-class-name: org.postgresql.Driver
server:
  port: 7777
s3:
  endpoint: endpoint
  region: region
  access-key: akey
  secret-key: skey
jwt:
  secret: secret_key
  cookieName: cookie_name
  expiration-days: 30