spring:
  profiles:
    active: local
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
    expiration-days: 7
  jpa:
    show-sql: true
    open-in-view: false
  application:
    name: steam-shop-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
s3:
  bucket: cars
  endpoint: https://s3.storage.selcloud.ru
  region: ru-1
  access-key: ${S3_ACCESS}
  secret-key: ${S3_SECRET}
server:
  port: 8443
jwt:
  secret: ${JWT_SECRET}
  cookieName: stsh_jwt
  expiration-days: 30
shop:
  id: ${SHOP_ID}
  token: ${SHOP_TOKEN}
  return-url: http://localhost:3000/products
cors:
  allowed-origins: http://localhost:3000