name: stsh backend pipeline

on:
  push:
    branches:
      - master

jobs:
  compile:
    runs-on: ubuntu-latest
    name: compilation
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'
      - name: compile
        run: ./mvnw clean compile

  build:
    runs-on: ubuntu-latest
    name: build backend
    needs: [compile]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'
      - name: build
        run: ./mvnw clean package

  build-docker:
    runs-on: ubuntu-latest
    name: build docker image
    needs: [ build ]
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'corretto'

      - name: extract project version
        id: extract_version
        run: echo "VERSION=$(./mvnw -q -Dexec.executable=echo -Dexec.args='${project.version}' -DnonRecursive exec:exec)" >> $GITHUB_OUTPUT

      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: build and push to ghcr.io
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/stsh-api:${{ steps.extract_version.outputs.VERSION }}
            ghcr.io/${{ github.repository_owner }}/stsh-api:latest
          build-args: |
            PROFILE=local
            VERSION=${{ steps.extract_version.outputs.VERSION }}
